### ISSUE TITLE
Undefined reference to signbit family functions

### ISSUE THREAD

**Issue by yxliang01** [srg-imperial/klee-float#1]
When building klee-float, the following tests are failing.

Failing Tests (13):                                                 
    KLEE :: Floats/fabs_double_symbolic.c                            
    KLEE :: Floats/fabs_float_symbolic.c                              
    KLEE :: Floats/fabs_long_double_symbolic.c                           
    KLEE :: Floats/fneg.c
    KLEE :: Floats/internal_fabs_double_symbolic.c
    KLEE :: Floats/internal_fabs_float_symbolic.c
    KLEE :: Floats/internal_fabs_long_double_symbolic.c
    KLEE :: Floats/internal_sqrt_double_symbolic.c
    KLEE :: Floats/internal_sqrt_float_symbolic.c
    KLEE :: Floats/internal_sqrt_long_double_symbolic.c
    KLEE :: Floats/sqrt_double_symbolic.c
    KLEE :: Floats/sqrt_float_symbolic.c
    KLEE :: Floats/sqrt_long_double_symbolic.c

The errors are "Error: external call with symbolic argument: __signbit" where `__signbit` sometimes is `__signbitf`, and so on. And, they are all `signbit` family functions. Adding `-libc=uclibc -libm` to the argument to the KLEE command made 9 failing tests passed and `fabs_long_double_symbolic`, `internal_fabs_long_double_symbolic.c`, `internal_sqrt_long_double_symbolic` and `sqrt_long_double_symbolic` are still failing. Indeed, the libm in klee-uclibc doesn't have any implementation for `__signbitl` which is what KLEE was complained about. However, I can see that a macro in https://github.com/klee/klee-uclibc/blob/c8efc9c36516d72fcdd24cb343c21cd302456893/include/math.h is trying to convert `signbit(long double)` to `__signbitl(long double)`.

I have the following questions:
1. Is klee-uclibc supposed to have an implementation for `__signbitl(long double)`?
2. Is my fix for those 9 previously failing tests appropriate? If not, what should be done instead?

Thanks a lot!

**Comment by ccadar** [comment]
@yxliang01 Sorry for the long delay in answering this. 
Not sure exactly why you're seeing these errors on your machine, most likely older versions of glibc defined `signbit`.  You could take a look at the Docker container to understand where the difference come from. E.g., how does the LLVM bitcode look like on your machine vs the Docker container?

**Comment by ccadar** [comment]
Closing this, but please reopen if still an issue
