### ISSUE TITLE
Error when running scripts/docker_aachen_build.sh -- gperftools install fail

### ISSUE THREAD

**Issue by wuruoyu** [srg-imperial/klee-float#6]
Hi,

I tried to build klee-float with docker but failed. It seems to me that the failure comes form `RUN pacman -Syy && pacman -S --noconfirm gperftools`. I am not familiar with Arch Linux, thus have no idea. I append a snippet below. Could you have a look? Thank you in advance!
```
Step 9/18 : RUN pacman -Syy && pacman -S --noconfirm gperftools
 ---> Running in 00f99f31b74e
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
resolving dependencies...
looking for conflicting packages...

Packages (1) gperftools-2.8-1

Total Download Size:   0.58 MiB
Total Installed Size:  2.40 MiB
Net Upgrade Size:      0.17 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
downloading gperftools-2.8-1-x86_64.pkg.tar.zst...
checking keyring...
checking package integrity...
loading package files...
error: could not open file /var/cache/pacman/pkg/gperftools-2.8-1-x86_64.pkg.tar.zst: Unrecognized archive format
error: failed to commit transaction (cannot open package file)
Errors occurred, no packages were upgraded.
The command '/bin/sh -c pacman -Syy && pacman -S --noconfirm gperftools' returned a non-zero code: 1
```

**Comment by danielschemmel** [comment]
The script performs an (unsupported) partial system upgrade on arch, which has finally started causing issues.

If you want to build on it, you will either have to download an old package by hand and install that (e.g., [from the package archive](https://wiki.archlinux.org/index.php/Arch_Linux_Archive#Finding_packages_in_the_Historical_Archive)), or perform a full upgrade of the base system.

Note, however, that this code is from about 4 years ago, and that other parts of it may cause problems (especially anything that does not run inside a container), as it is not actively maintained. See also #5.

**Comment by wuruoyu** [comment]
Thank you for your reply!
